version: "3.8"

volumes:
  mariadb_data:

services:
  database:
    image: mariadb:10.7
    container_name: "mariadb"
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network
    environment:
      MYSQL_ROOT_PASSWORD: rand528PASS-wd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin"
    ports:
      - "8088:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: rand528PASS-wd
      UPLOAD_LIMIT: 500M
    networks:
      - app_network
    depends_on:
      - database
    volumes:
      - /proc/meminfo:/proc/meminfo:ro
      - /proc/stat:/proc/stat:ro

  gpt4all:
    build:
      context: ./genai/gpt4all
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - genai-network

  weaviate:
    build:
      context: ./genai/weaviate
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50051:50051"
    networks:
      - genai-network

networks:
  app_network:
    driver: bridge
  genai-network:
    driver: bridge