global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'spring-backend'
    static_configs:
      - targets: ['host.docker.internal:1111']

  - job_name: 'weaviate'
    static_configs:
      - targets: ['weaviate:8080']

  - job_name: 'gpt4all'
    static_configs:
      - targets: ['gpt4all:5000']
    metrics_path: '/metrics'
    params:
      format: ['prometheus']
    scheme: 'http'

  - job_name: 'cadvisor'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    metrics_path: /metrics/cadvisor
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
