global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090', 'prometheus:8081']

  - job_name: 'spring-backend'
    static_configs:
      - targets: ['host.docker.internal:1111']

  - job_name: 'weaviate'
    static_configs:
      - targets: ['weaviate:8081']

  - job_name: 'phpmyadmin'
    static_configs:
      - targets: ['phpmyadmin:8081']

  - job_name: 'database'
    static_configs:
      - targets: ['database:8081']

  - job_name: 'gpt4all'
    static_configs:
      - targets: ['gpt4all:5000', 'gpt4all:8081']
    metrics_path: '/metrics'
    params:
      format: ['prometheus']
    scheme: 'http'

  - job_name: 'cadvisor-docker'
    static_configs:
      - targets: ['cadvisor:8081']