apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: cadvisor