apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      component: database
  template:
    metadata:
      labels:
        app: database
        component: database
    spec:
      containers:
        - name: database
          image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.database.rootPassword }}
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
        - name: cadvisor
          image: {{ .Values.cadvisor.image.repository }}:{{ .Values.cadvisor.image.tag }}
          imagePullPolicy: {{ .Values.cadvisor.image.pullPolicy }}
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: varrun
              mountPath: /var/run
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: dockersock
              mountPath: /var/lib/docker
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: varrun
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: dockersock
          hostPath:
            path: /var/lib/docker
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
      restartPolicy: Always