apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      component: database
  template:
    metadata:
      labels:
        app: database
        component: database
    spec:
      containers:
        - name: database
          image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.database.rootPassword }}
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
      restartPolicy: Always