apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: cadvisor
  selector:
    app: database