apiVersion: v1
kind: Service
metadata:
  name: gpt4all
  labels:
    app: gpt4all
    chart: {{ include "wiki.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: cadvisor
  selector:
    app: gpt4all