apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki.fullname" . }}-gpt4all
  labels:
    app: {{ include "wiki.name" . }}
    chart: {{ include "wiki.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: {{ include "wiki.name" . }}
    component: gpt4all