apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki.fullname" . }}-grafana
  labels:
    {{- include "wiki.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "wiki.name" . }}
    component: grafana