{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-api-ingress"        # Changed from -ingress to -api-ingress
  {{- $annotations := .Values.ingress.annotations | default dict }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- toYaml $annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.ingress.host }}"
      secretName: "{{ .Release.Name }}-tls"
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: server
                port:
                  number: 1111
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-frontend-ingress"   # Changed from -wiki-ingress to -frontend-ingress
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: 80
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
{{- end }}