apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
    component: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
      component: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
        component: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: {{ .Values.phpmyadmin.image.repository }}:{{ .Values.phpmyadmin.image.tag }}
          imagePullPolicy: {{ .Values.phpmyadmin.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: {{ .Values.phpmyadmin.host }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.database.rootPassword }}
            - name: UPLOAD_LIMIT
              value: {{ .Values.phpmyadmin.uploadLimit }}
          volumeMounts:
            - name: proc-meminfo
              mountPath: /proc/meminfo
              readOnly: true
            - name: proc-stat
              mountPath: /proc/stat
              readOnly: true
      volumes:
        - name: proc-meminfo
          hostPath:
            path: /proc/meminfo
        - name: proc-stat
          hostPath:
            path: /proc/stat