apiVersion: v1
kind: Service
metadata:
  name: weaviate
  labels:
    app: weaviate
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: cadvisor
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
  selector:
    app: weaviate