apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  labels:
    app: weaviate
spec:
  replicas: {{ .Values.weaviate.replicaCount }}
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
        - name: weaviate
          image: {{ .Values.weaviate.image.repository }}:{{ .Values.weaviate.image.tag }}
          imagePullPolicy: {{ .Values.weaviate.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: WEAVIATE_HOST
              value: "0.0.0.0"
            - name: WEAVIATE_PORT
              value: "8080"
            - name: WEAVIATE_AUTHENTICATION
              value: "false"
          resources:
            {{- toYaml .Values.weaviate.resources | nindent 12 }}