name: Deploy Helm Chart to Rancher

on:
  #workflow_run:
    #workflows: ["Build and Publish Docker Images"]
    #types:
    #  - completed
  push:
    branches:
      - main
      - 47-workflow-bugfix

jobs:
  deploy:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.0' 

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Create kubeconfig file
        run: echo "${{ secrets.KUBECONFIG_DATA }}" > ${{ github.workspace }}/kubeconfig

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Deploy Helm Chart
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          helm upgrade --install wiki ./helm/wiki --namespace wiki --create-namespace

      - name: Verify Deployment
        env:
            KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          kubectl get pods -n wiki