name: Test genai

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: genai/gpt4all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi[all] pytest requests weaviate-client gpt4all prometheus-fastapi-instrumentator

      - name: Run tests
        run: pytest test_genAI.py